id: PE8F948CF
initial_creation_type: ocr
source_metadata:
  volumes:
    8d3f6f8275744daa825fed7670b22a15:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: བླ་ན་མེད་པའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
